name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install prereqs
      run: |
        sudo apt-get update
        sudo apt-get install build-essential nasm bash

    - name: Test
      run: |
        make test

